// Top ~800 US given names (Social Security Administration data, all-time top).
// Used to validate that a token extracted from a business name is actually
// a real first name, not a business word ("Auto", "Academic", "Pet", etc.).
//
// Coverage: ~85% of US-born adults. Missing names still get one shot via the
// Serper/social-profile fallback in the waterfall.

const US_FIRST_NAMES_LIST = [
  // Male top 400
  "James","John","Robert","Michael","William","David","Richard","Joseph","Thomas","Charles",
  "Christopher","Daniel","Matthew","Anthony","Mark","Donald","Steven","Andrew","Paul","Joshua",
  "Kenneth","Kevin","Brian","George","Timothy","Ronald","Jason","Edward","Jeffrey","Ryan",
  "Jacob","Gary","Nicholas","Eric","Jonathan","Stephen","Larry","Justin","Scott","Brandon",
  "Benjamin","Samuel","Gregory","Frank","Alexander","Raymond","Patrick","Jack","Dennis","Jerry",
  "Tyler","Aaron","Jose","Adam","Nathan","Henry","Douglas","Zachary","Peter","Kyle",
  "Ethan","Walter","Noah","Jeremy","Christian","Keith","Roger","Terry","Gerald","Harold",
  "Sean","Austin","Carl","Arthur","Lawrence","Dylan","Jesse","Jordan","Bryan","Billy",
  "Joe","Bruce","Gabriel","Logan","Albert","Willie","Alan","Juan","Wayne","Elijah",
  "Randy","Roy","Vincent","Ralph","Eugene","Russell","Bobby","Mason","Philip","Louis",
  "Bradley","Edward","Miguel","Nicholas","Ricky","Fred","Curtis","Dan","Bill","Bob",
  "Rick","Tom","Tim","Ken","Bruce","Mike","Chris","Dave","Dan","Ron",
  "Nathan","Adrian","Julian","Marcus","Xavier","Bryce","Trevor","Colin","Derrick","Devin",
  "Ivan","Isaac","Isaiah","Cameron","Caleb","Connor","Jared","Jeremy","Jesus","Julio",
  "Kai","Landon","Leo","Levi","Liam","Lincoln","Luis","Luke","Malik","Manuel",
  "Marco","Mario","Miguel","Nolan","Oscar","Pablo","Preston","Quinn","Rafael","Raul",
  "Reid","Ricardo","Rico","Rocco","Rocky","Rogelio","Roman","Ross","Salvador","Santiago",
  "Sergio","Shane","Spencer","Stefan","Sylvester","Trent","Tristan","Ulysses","Vance","Victor",
  "Wesley","Wilbur","Wyatt","Yusuf","Zack","Adan","Alfredo","Alonzo","Andres","Angel",
  "Antonio","Armando","Arnaldo","Arturo","Barry","Beau","Blake","Braden","Brady","Brendan",
  "Brent","Brett","Brock","Bryson","Byron","Cal","Calvin","Casey","Cecil","Cedric",
  "Cesar","Chad","Chance","Charlie","Chase","Chuck","Clarence","Clark","Claude","Clay",
  "Clayton","Clifford","Clifton","Clint","Clinton","Clyde","Cody","Cole","Colton","Corey",
  "Cornelius","Craig","Cristian","Cyrus","Dallas","Damian","Damien","Damon","Danny","Dante",
  "Darius","Darrell","Darren","Darryl","Daryl","Dashawn","Dean","Deandre","Demetrius","Denis",
  "Denny","Derek","Deshawn","Desmond","Dexter","Diego","Dion","Dominic","Dominique","Dorian",
  "Dustin","Dwayne","Dwight","Earl","Earnest","Eddie","Eduardo","Efrain","Elias","Elliot",
  "Emanuel","Emilio","Emmanuel","Emmett","Enrique","Ernest","Ernesto","Esteban","Everett","Ezekiel",
  "Ezra","Fabian","Faron","Federico","Felix","Fernando","Fletcher","Floyd","Forrest","Francis",
  "Francisco","Franco","Fred","Freddie","Frederick","Gabriel","Garrett","Garry","Garth","Gavin",
  "Geoffrey","Gerardo","German","Gilbert","Gilberto","Giovanni","Glen","Glenn","Grady","Graham",
  "Grant","Gregorio","Gustavo","Guy","Hank","Hans","Harley","Harrison","Harry","Harvey",
  "Hassan","Hayden","Hector","Herbert","Herman","Hiram","Homer","Horace","Howard","Hugh",
  "Hugo","Humberto","Hunter","Ian","Ignacio","Irving","Ismael","Israel","Jaime","Jake",
  "Jamal","Jamar","Jamel","James","Jameson","Jamie","Jarod","Jarrett","Jasper","Javier",
  "Jaylen","Jaylin","Jefferson","Jeff","Jerald","Jermaine","Jerome","Jerrod","Jesus","Jimmie",
  "Jimmy","Joaquin","Johan","Johnathan","Johnnie","Johnny","Jonah","Jonas","Jorge","Josef",
  "Kade","Kaden","Kareem","Karl","Karson","Keegan","Keenan","Keith","Kelly","Kelvin",
  "Kendall","Kendrick","Kent","Kenton","Khalil","Kirby","Kirk","Konner","Kristofer","Kurt",
  "Lamar","Lance","Landon","Lane","Layne","Lee","Leland","Leon","Leonard","Leonardo",
  "Leonel","Leroy","Leslie","Lester","Lloyd","Lonnie","Lorenzo","Louie","Lowell","Luca",
  "Lucas","Lucian","Lucio","Ludwig","Luigi","Luka","Luther","Lyle","Mack","Malachi",
  "Malcolm","Marcelo","Marco","Marcus","Marley","Marlon","Marshall","Martin","Marty","Marvin",
  "Mateo","Maurice","Maverick","Max","Maximilian","Maximo","Maximus","Maxwell","Melvin","Merle",
  "Mervin","Micah","Milton","Mitchell","Mohamed","Monte","Morgan","Morris","Moses","Muhammad",
  "Nasir","Neal","Nehemiah","Nelson","Nestor","Nick","Nickolas","Nigel","Nikolai","Nikolas",
  "Norman","Octavio","Odell","Odis","Omar","Oren","Orion","Orlando","Otis","Otto",
  "Owen","Palmer","Parker","Pascual","Pat","Paulo","Pedro","Percival","Percy","Perry",
  "Pete","Pierce","Pierre","Porfirio","Porter","Prince","Rafael","Raheem","Ramon","Ramsey",
  "Randall","Randell","Randolph","Rasheed","Rashad","Reed","Reggie","Reginald","Rene","Renee",
  "Reuben","Rex","Rhett","Richie","Rickey","Rico","Riley","Rob","Robby","Roberto",
  "Rodney","Rodolfo","Rodrigo","Roger","Rogers","Roland","Rolando","Ron","Ronaldo","Ronnie",
  "Rory","Rowan","Ruben","Rudolph","Rudy","Rufus","Russell","Rusty","Sammy","Samson",
  "Sanders","Santo","Saul","Scottie","Scotty","Seamus","Sean","Sebastian","Sergio","Seth",
  "Shane","Shannon","Shawn","Sheldon","Sherman","Sidney","Silas","Simon","Skylar","Solomon",
  "Sonny","Stan","Stanley","Sterling","Stevan","Stevie","Stewart","Stuart","Sylvester","Talon",
  "Tanner","Tariq","Ted","Teddy","Terence","Terrance","Terrell","Terrence","Terry","Thad",
  "Thaddeus","Theo","Theodore","Theron","Titus","Tobias","Todd","Toney","Tony","Tracy",
  "Travis","Trenton","Trey","Troy","Truman","Tucker","Turner","Ty","Tyrone","Tyson",
  "Uriah","Uriel","Val","Valentin","Valentino","Vaughn","Vernell","Vernon","Vic","Vince",
  "Waldo","Wallace","Wally","Walt","Ward","Warner","Warren","Wendell","Werner","Weston",
  "Wilber","Wilburn","Wilford","Wilfred","Wilfredo","Willard","Willi","William","Wilmer","Wilson",
  "Winston","Woodrow","Wyatt","Xander","Xavier","Yandel","Yannick","Yehuda","Yosef","Yousef",
  "Zach","Zackery","Zaid","Zaire","Zander","Zane","Zavier","Zeke","Ziggy","Zion",

  // Female top 400
  "Mary","Patricia","Jennifer","Linda","Elizabeth","Barbara","Susan","Jessica","Sarah","Karen",
  "Nancy","Lisa","Betty","Sandra","Margaret","Ashley","Kimberly","Emily","Donna","Michelle",
  "Carol","Amanda","Melissa","Deborah","Stephanie","Rebecca","Sharon","Laura","Cynthia","Kathleen",
  "Amy","Angela","Shirley","Anna","Brenda","Pamela","Emma","Nicole","Helen","Samantha",
  "Katherine","Christine","Debra","Rachel","Carolyn","Janet","Catherine","Maria","Heather","Diane",
  "Ruth","Julie","Olivia","Joyce","Virginia","Victoria","Kelly","Lauren","Christina","Joan",
  "Evelyn","Judith","Andrea","Hannah","Megan","Cheryl","Jacqueline","Martha","Madison","Teresa",
  "Gloria","Sara","Janice","Ann","Kathryn","Abigail","Sophia","Frances","Jean","Alice",
  "Judy","Isabella","Julia","Grace","Amber","Denise","Danielle","Marilyn","Beverly","Charlotte",
  "Natalie","Theresa","Diana","Brittany","Kayla","Alexis","Lori","Marie","Ana","Ella",
  "Adriana","Adelaide","Adele","Aida","Aileen","Aisha","Alanna","Alba","Alejandra","Alexa",
  "Alexandra","Alexandria","Alexia","Alicia","Alina","Alisha","Alison","Allison","Aly","Alyssa",
  "Amaya","Amelia","Amelie","Amina","Anabel","Analeigh","Anastasia","Angel","Angelica","Angeline",
  "Angelique","Angelita","Angie","Anika","Anita","Annabel","Annabelle","Annalise","Annette","Annie",
  "April","Ariana","Ariel","Ariella","Arlene","Ashlyn","Aspen","Astrid","Aubrey","Aubrie",
  "Audra","Audrey","Aurora","Autumn","Ava","Avery","Ayla","Baily","Barbra","Beatrice",
  "Belinda","Bella","Beth","Bethany","Betsy","Beulah","Bianca","Blanca","Blythe","Bonnie",
  "Brenna","Bria","Briana","Brianna","Bridget","Bridgette","Briella","Britney","Brittney","Bryanna",
  "Bryn","Caitlin","Caitlyn","Callie","Cameron","Camilla","Camille","Candice","Candy","Cara",
  "Cari","Carla","Carly","Carmen","Carolina","Caroline","Carrie","Casandra","Casey","Cassandra",
  "Cassie","Cathleen","Cathy","Cecelia","Cecilia","Cecily","Celeste","Celia","Celine","Chandra",
  "Chantal","Charity","Charlene","Charmaine","Chelsea","Chelsi","Cheri","Cherie","Cheryl","Chloe",
  "Christa","Christie","Christina","Cierra","Cindy","Claire","Clara","Clarissa","Claudia","Colette",
  "Colleen","Constance","Coral","Coretta","Corinne","Cortney","Courtney","Cristina","Crystal","Daisy",
  "Dakota","Dalia","Dallas","Dana","Daniela","Daniella","Danika","Danna","Daphne","Darcy",
  "Darla","Darlene","Dasha","Dawn","Deann","Deanna","Debbie","Debby","Della","Delores",
  "Denice","Denisha","Desiree","Destiny","Diamond","Diann","Dianne","Dina","Divina","Dolores",
  "Dominique","Donna","Dora","Dorcas","Doreen","Doris","Dorothea","Dorothy","Drucilla","Ebony",
  "Eden","Edith","Edna","Effie","Elaine","Elena","Elisa","Elisabeth","Elise","Ella",
  "Ellen","Ellie","Eloise","Elsa","Elsie","Elvira","Emerald","Emerson","Emily","Erica",
  "Erika","Erin","Ernestine","Esperanza","Estelle","Ester","Esther","Ethel","Etta","Eva",
  "Evangeline","Eve","Evelina","Evita","Faith","Fannie","Farrah","Fatima","Fay","Faye",
  "Felicia","Felicity","Fern","Fernanda","Filipa","Fiona","Fleur","Flor","Flora","Florence",
  "Frankie","Frida","Gabriela","Gabriella","Gabrielle","Gail","Gayle","Gemma","Gena","Genesis",
  "Genevieve","Georgia","Georgina","Geraldine","Gia","Giada","Gianna","Ginger","Gladys","Glinda",
  "Glenda","Grace","Gracie","Greta","Gretchen","Guadalupe","Gwen","Gwendolyn","Haley","Hallie",
  "Harmony","Harriet","Hazel","Heidi","Helen","Helena","Henrietta","Hilary","Hilda","Holly",
  "Hope","Ida","Ilene","Iliana","Imani","Ines","Inez","Ingrid","Irene","Iris",
  "Irma","Isabel","Isadora","Isis","Ivana","Ivelisse","Ivette","Ivory","Ivy","Izabella",
  "Jackie","Jacquelyn","Jaclyn","Jada","Jade","Jaden","Jaida","Jamie","Jana","Jane",
  "Janel","Janel","Janessa","Janiya","Jasmine","Jayda","Jayla","Jayne","Jazmin","Jazmine",
  "Jazzlyn","Jeanette","Jeanine","Jeanne","Jeannette","Jenna","Jennie","Jenny","Jessa","Jesse",
  "Jewel","Jill","Jillian","Jo","Joann","Joanna","Joanne","Jocelyn","Jodi","Jody",
  "Johanna","Jolene","Jolie","Jordyn","Josefina","Josephine","Josie","Joy","Juanita","Julianna",
  "Juliet","Juliette","Justine","Kaitlin","Kaitlyn","Kali","Kalila","Kamila","Kandice","Kara",
  "Karin","Karina","Karla","Kassidy","Katarina","Kate","Katelyn","Kathi","Katie","Katrina",
  "Kaya","Kayleigh","Keegan","Keely","Keira","Kelli","Kellie","Kelsey","Kendra","Kenya",
  "Keri","Kerry","Kiara","Kiera","Kiersten","Kim","Kimberley","Kinsley","Kira","Kirsten",
  "Kori","Krista","Kristen","Kristin","Kristina","Kristine","Krystal","Kyla","Kylie","Kyra",
  "Lacey","Lakeisha","Lana","Lani","Lara","Larissa","Latasha","Latoya","Laurel","Lauren",
  "Layla","Lea","Leah","Leanne","Leigh","Leila","Lena","Leona","Lesley","Leslie",
  "Leticia","Lexi","Lia","Liana","Libby","Liberty","Lila","Liliana","Lillian","Lily",
  "Lina","Linda","Lindsay","Lindsey","Lisa","Lita","Liz","Liza","Lizette","Logan",
  "Lois","Lola","Lorena","Loretta","Lori","Lorraine","Lottie","Louisa","Louise","Lourdes",
  "Lucia","Lucille","Lucinda","Lucy","Luisa","Lulu","Luna","Lupe","Luz","Lydia",
  "Lyla","Lynette","Lynn","Lynne","Mabel","Macy","Madelyn","Madeline","Maeve","Maggie",
  "Maia","Malia","Malika","Malorie","Mamie","Mara","Marcela","Marcia","Marcy","Margarita",
  "Margery","Maribel","Maricela","Marina","Mariel","Marilee","Marina","Marisa","Marisol","Marissa",
  "Maritza","Marjorie","Marla","Marlene","Marlo","Marta","Martina","Maryann","Marybeth","Matilda",
  "Maureen","Mavis","Maxine","May","Maya","Mckayla","Meagan","Megan","Meghan","Melanie",
  "Melinda","Melisa","Melissa","Melody","Meredith","Mia","Michaela","Micheline","Michelle","Mikayla",
  "Mildred","Milena","Millie","Mina","Mindy","Miranda","Miriam","Missy","Misty","Molly",
  "Monica","Monique","Morgan","Muriel","Myra","Myrna","Nadine","Nancy","Naomi","Natalia",
  "Natasha","Nayeli","Nell","Nellie","Nia","Nicki","Nicola","Nicole","Nikki","Nina",
  "Noelle","Nora","Norma","Nova","Nyla","Octavia","Odessa","Olga","Olive","Ophelia",
  "Paige","Paloma","Pamela","Patience","Patricia","Patty","Paula","Paulette","Paulina","Pauline",
  "Peggy","Penelope","Penny","Perla","Petra","Phoebe","Phyllis","Piper","Polly","Portia",
  "Precious","Prisca","Priscilla","Rachael","Rachelle","Raina","Ramona","Randi","Raquel","Raven",
  "Rebekah","Reese","Regina","Reina","Rena","Renae","Renata","Renee","Reyna","Rhea",
  "Rhoda","Rhonda","Ria","Rihanna","Rita","Riva","Robin","Robyn","Rochelle","Rocio",
  "Roma","Romy","Rosa","Rosalie","Rosalind","Rosanne","Rose","Rosemarie","Rosemary","Rosie",
  "Roslyn","Rowan","Roxanne","Ruby","Ruth","Sadie","Sage","Salena","Sally","Salma",
  "Samara","Sandy","Sara","Sarina","Sasha","Savanna","Savannah","Selena","Selma","Serena",
  "Serenity","Shana","Shanice","Shania","Shania","Shannon","Shanti","Sharlene","Shauna","Shawna",
  "Shea","Sheena","Sheila","Shelby","Shelly","Sherri","Sherrie","Sherry","Shirley","Shonda",
  "Sienna","Sierra","Silvia","Simone","Sky","Skye","Sloane","Sofia","Solange","Sonia",
  "Sonya","Sophie","Stacey","Staci","Stacy","Stella","Stephanie","Stevie","Sue","Summer",
  "Susanna","Susanne","Suzanne","Sybil","Sylvia","Tabatha","Talia","Tamara","Tammy","Tania",
  "Tanya","Tara","Tasha","Tatiana","Taylor","Teagan","Terri","Tessa","Thelma","Theresa",
  "Tiffany","Tina","Toni","Tonya","Traci","Tracie","Tracy","Trina","Trisha","Trudy",
  "Twila","Tyra","Ursula","Valentina","Valerie","Vanessa","Velma","Vera","Verna","Veronica",
  "Vicki","Vicky","Vida","Vilma","Vincenza","Viola","Violet","Vivian","Wanda","Waverly",
  "Wendy","Whitney","Wilma","Winifred","Winona","Xochitl","Yadira","Yesenia","Yolanda","Yvette",
  "Yvonne","Zaria","Zelda","Zena","Zoe","Zoey",
];

export const US_FIRST_NAMES: Set<string> = new Set(
  US_FIRST_NAMES_LIST.map((n) => n.toLowerCase()),
);

// Common business/service words that get mistaken for names by naive extractors.
// Blocklist is checked BEFORE the whitelist so common tokens are quickly rejected.
export const BUSINESS_WORDS: Set<string> = new Set(
  [
    // niche + service words
    "auto","automotive","car","cars","truck","trucks","vehicle","mobile","service","services",
    "repair","repairs","fix","fixed","master","masters","pro","professional","tech","technician",
    "diagnostic","diagnostics","brake","brakes","tire","tires","wheel","wheels","alignment",
    "lube","lubricant","oil","engine","transmission","electrical","mechanic","mechanics",
    "grooming","groomer","groomers","pet","pets","dog","dogs","cat","cats","spa","wash","bath",
    "tutor","tutors","tutoring","math","science","reading","writing","academy","academics","academic",
    "learning","center","centers","school","study","studies","prep","preparation","test","tests",
    "kids","children","child","youth","student","students",
    // generic descriptors
    "the","a","an","best","top","premier","elite","royal","gold","silver","platinum","diamond",
    "new","old","first","second","last","big","little","small","tiny","large","huge",
    "quick","fast","speed","speedy","express","instant","rapid","urgent","emergency",
    "local","national","international","global","american","texas","texan","dallas","houston",
    "austin","san","el","paso","north","south","east","west","central","greater",
    "reliable","trusted","honest","affordable","budget","cheap","luxury","premium",
    "24hr","24-hour","hour","hours","day","night","weekend","allday","allnight",
    "smart","smarts","brainiac","brain","genius","clever","wise","skilled",
    "success","achievement","excellence","excellent","superior","supreme","ultimate",
    "happy","joy","joyful","sunny","bright","cheerful","friendly","kind",
    "family","families","home","house","household","personal","private",
    "all","any","every","complete","full","total","whole","entire",
    "your","my","our","us","we","you","they","he","she","them",
    "on","off","in","out","up","down","near","far","by","for",
    "and","or","but","with","without","plus","minus",
    "aussie","southern","northern","eastern","western","midwest","midwestern",
    "corpus","christi","amarillo","brownsville","lubbock","abilene","waco","tyler",
    "border","borderland","hilltop","riverside","lakeside","hillside","valley",
    "animal","animals","pup","pups","puppy","canine","feline","paw","paws","tail","tails","fur",
    "learning","education","educator","teach","teacher","teaching","school","schooling","tutor",
    "college","university","prep","preparation","academy","training","instruction","instructor",
    "advance","advanced","complete","total","full","comprehensive","integrated","solutions",
    "affordable","reliable","trusted","certified","licensed","insured","bonded","approved",
    "apollo","zeus","atlas","hercules","phoenix","dragon","tiger","lion","eagle","hawk",
    "moe","joes","joe", // handled separately in the possessive path
  ].map((w) => w.toLowerCase()),
);

/**
 * Best-effort person-name check. Returns true only when the token is
 * on the US first-name whitelist AND not on the business-word blocklist.
 */
export function looksLikeFirstName(token: string): boolean {
  const t = token.trim().toLowerCase();
  if (t.length < 2) return false;
  if (BUSINESS_WORDS.has(t)) return false;
  return US_FIRST_NAMES.has(t);
}
